### PR TITLE
WEB-17: get the user's current location

### PR DESCRIPTION
**Pull request by jennyckaplan**
Creates the loading screen and starts/ends the run at the user's current location. Created a new ticket to handle the loading state/async functions in a cleaner way, but I think this works for now. 

#### Loading State
ezgif-1-d426d64469b1
#### Current Location (in San Francisco since it is the simulator's default current location)
ezgif-1-232938c51d44
#### Check location permission
Screen Shot 2019-10-24 at 10 44 44 AM

### CODE REVIEW

**Comment by rlamsal1256** [comment]
Does this work even if the user's location is turned off?

**Comment by rlamsal1256** [comment]
Are these changes only of ios? if so, should we create another ticket for android?

**Comment by rlamsal1256** [comment]
loading indicator seems unnecessary and flickery going from first to second screen (as shown in the demo) if its always only going to be shown for less than a second?

**Comment by jennyckaplan** [comment]
> Are these changes only of ios? if so, should we create another ticket for android?

going to update this PR to work for Android. Also will create an error state if the user's location is turned off. Pretty sure it will get stuck in the loading state if the user's location is turned off. I agree, the loading state is only there for a short amount of time sometimes but at other times it takes a bit longer. I think once I clean up the async initState then the loading state won't be necessary so I'll take it out here but I'll keep it in the codebase in case we need it later.

**Comment by rlamsal1256** [comment]
> going to update this PR to work for Android. Also will create an error state if the user's location is turned off. Pretty sure it will get stuck in the loading state if the user's location is turned off. I agree, the loading state is only there for a short amount of time sometimes but at other times it takes a bit longer. I think once I clean up the async initState then the loading state won't be necessary so I'll take it out here but I'll keep it in the codebase in case we need it later.

Another option could be to get user's current location on the first screen?

**Comment by jennyckaplan** [comment]
> > going to update this PR to work for Android. Also will create an error state if the user's location is turned off. Pretty sure it will get stuck in the loading state if the user's location is turned off. I agree, the loading state is only there for a short amount of time sometimes but at other times it takes a bit longer. I think once I clean up the async initState then the loading state won't be necessary so I'll take it out here but I'll keep it in the codebase in case we need it later.
> 
> Another option could be to get user's current location on the first screen?

But if we implement a way to choose your start/end location instead of assuming current location, then it would make sense to put it on this page right? in case we have a button to grab the current location?

**Comment by rlamsal1256** [comment]
> > > going to update this PR to work for Android. Also will create an error state if the user's location is turned off. Pretty sure it will get stuck in the loading state if the user's location is turned off. I agree, the loading state is only there for a short amount of time sometimes but at other times it takes a bit longer. I think once I clean up the async initState then the loading state won't be necessary so I'll take it out here but I'll keep it in the codebase in case we need it later.
> > 
> > 
> > Another option could be to get user's current location on the first screen?
> 
> But if we implement a way to choose your start/end location instead of assuming current location, then it would make sense to put it on this page right? in case we have a button to grab the current location?

okay, yup. this should be fine then. doesn't look like it takes a long time to access the current location so nbd

**Pull request merged**
